### PR TITLE
Fixes no eggs incubating crash.

### PR DESCRIPTION
**Pull request by TremendousTurtle**
The farm mode check now only checks pokeballs of which the trainer is able to obtain.

I also adjusted the similar pokemon filter to actually check CP values before transferring. Now it will only release pokemon with CP lower than the KEEP_CP_OVER value no matter what their IV % is.

### CODE REVIEW

**Comment by BoBeR182** [comment]
Please split pull requests into one per issue.

**Comment by BoBeR182** [comment]
Fix TravisCI and I'll merge.

**Comment by BoBeR182** [comment]
I'm going to close this and just merge your Commit for the egg fix by hand, you need to create one PR per Issue, or use branches to not change your existing PR.

**Comment by TremendousTurtle** [comment]
Sorry I didn't know that committing to my master branch would change my pull request.

**Comment by BoBeR182** [comment]
Hence why people make the PR just of the branch, I'm new to developing too, just look at the history of commits.

**Pull request closed without merging**
